# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b479cc51699df5683f9e2bbc4b79db74bfb6f4f443c7dad16c8768a352b1897d2ff8246d7410104101931521151f06c8e3f27c0e1629e10df1cd3d301230b64b

test:
  secret_key_base: 31642a7b1b6666ce1593c2bb4c3c5198aab2a39c36c89b5aa8bbe2797189f97e88ecc15941d798d76bb600e974de320b390e14a247981bcdd2cf802975c6669b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
